branch-defaults:
  main:
    environment: Titanium-Site-env-3
    group_suffix: null
environment-defaults:
  Titanium-Site-env-2:
    branch: null
    repository: null
  Titanium-Site-env-3:
    branch: null
    repository: null
global:
  application_name: Titanium-Site-env
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.11 running on 64bit Amazon Linux 2023
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
